/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_tinydew4_errno_list_ErrnoListActivity */

#ifndef _Included_kr_co_tinydew4_errno_list_ErrnoListActivity
#define _Included_kr_co_tinydew4_errno_list_ErrnoListActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_co_tinydew4_errno_list_ErrnoListActivity
 * Method:    NDKErrnoToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_tinydew4_errno_1list_ErrnoListActivity_NDKErrnoToString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
