/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_tinydew4_ifconfig_IfconfigActivity */

#ifndef _Included_kr_co_tinydew4_ifconfig_IfconfigActivity
#define _Included_kr_co_tinydew4_ifconfig_IfconfigActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_co_tinydew4_ifconfig_IfconfigActivity
 * Method:    NDKIfconfig
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_tinydew4_ifconfig_IfconfigActivity_NDKIfconfig
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
